# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ProyextoValizas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProyextoValizas

  target 'ProyextoValizasTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'ProyextoValizasUITests' do
    inherit! :search_paths
    # Pods for testing
  end

	
pod 'SRCountdownTimer'



end
